# Generated by Django 4.2.6 on 2023-10-16 23:47

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_created_at_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 400}}, verbose_name='Image'),
        ),
    ]
